### ISSUE TITLE
Support creation of CodeSystems

### ISSUE THREAD

**Issue by Semalexa** [HealthSamurai/ig-ae#14]
Support generation of CodeSystem resources.

**Comment by qdzo** [comment]
Added support in 999a4302936b9fcca0dc47ab668490d80d5a3f34

Need verification for correctness

**Comment by Semalexa** [comment]
Done.

How to create a new CodeSystem
Create a yaml file with the cs. prefix in the src folder. The template looks as follows:

```yaml
description: Defines possible condition outcomes
content: complete
title: Condition Outcome
name: ConditionOutcome
version: 0.1.0
status: active
date: 2021-01-19T13:20:31+00:00
publisher: AstraZeneca
concepts:
- code: resolved
  display: Resolved
- code: recovering
  display: Recovering
- code: ongoing
  display: Ongoing
- code: resolvedWithSequelae
  display: Resolved with Sequelae
- code: fatal
  display: Fatal
- code: unknown
  display: Unknown
- code: recovered
  display: Recovered
```
