### ISSUE TITLE
Необходимо убрать элементы title, experimental, date, publisher из StructureDefinition.differential профиля на ресурс

### ISSUE THREAD

**Issue by Semalexa** [HealthSamurai/ig-ae#9]
Необходимо в описании расширений поддержать элементы [title, experimental, date, publisher], которые при генерации StructureDefinition должны попасть в корень ресурса StructureDefinition профиля расширения и не должны попасть в StructureDefinition.differential профиля на ресурс.

Например в igpop профиле задано расшериние:

```
elements:
  extension:
    ethnicity:
      description: Patient Ethnicity Extension
      type: CodeableConcept
      title: AZ Patient Ethnicity Extension
      experimental: false
      date: "2020-12-18"
      publisher: AstraZeneca 
      valueset:
        id: detailed-ethnicity
        description: The value should be from the valueset detailed-ethnicity
```

Элементы title, experimental, date, publisher должны попасть в файл StructureDefinition\hl7.fhir.ae-Patient-ethnicity.json (это сейчас работает) и не должны попасть в StructureDefinition\hl7.fhir.ae-Patient.json в StructureDefinition.differential (сейчас попадают туда).

Полный список корневых элементов StructureDefinition, которые могут быть заданы вручную при описании расширений:
* identifier
* version
* name
* title
* status
* experimental
* date
* publisher
* contact
* description
* useContext
* jurisdiction
* purpose
* copyright
* keyword
* fhirVersion
* mapping
* kind
* abstract
* context
* contextInvariant
* type
* baseDefinition
* derivation

![notepad++_3mmBCXR7lU](https://user-images.githubusercontent.com/345535/102605512-ff056280-40ea-11eb-8113-02be2341c91e.png)
